name: Test @upstash/redis compatability
on:
  push:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:18
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      srh:
        image: hiett/serverless-redis-http:latest
        volumes:
          - ./example/srh-config.json:/app/srh-config/tokens.json
        ports:
          - 8080:80

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./example
        run: yarn install

      - name: Run script
        working-directory: ./example
        run: yarn start
