name: Test @upstash/redis compatability
on:
  workflow_dispatch:
  push:
#    paths:
#      - 'lib/**'
  schedule:
    - cron: '0 12 * * *'

env:
  SRH_TOKEN: example_token

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SRH code
        uses: actions/checkout@v3

      - name: Build Dockerfile
        run: docker build -t hiett/serverless-redis-http:latest .

      - name: Export to TAR
        run: docker save hiett/serverless-redis-http:latest -o /tmp/serverless-redis-http.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: serverless-redis-http
          path: /tmp/serverless-redis-http.tar

  container-job:
    runs-on: ubuntu-latest
    container: denoland/deno
    needs: build
    services:
      redis:
        image: redis/redis-stack-server:6.2.6-v6 # 6.2 is the Upstash compatible Redis version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: upstash/upstash-redis

      - name: Download SRH artifact
        uses: actions/download-artifact@v3
        with:
          name: serverless-redis-http
          path: /tmp

      - name: Load SRH image
        run: |
          docker load --input /tmp/serverless-redis-http.tar
          docker image ls -a

      - name: Run SRH container
        uses: addnab/docker-run-action@v3
        with:
          image: hiett/serverless-redis-http:latest
          options: -it -d -e SRH_MODE=env -e SRH_TOKEN=${{ env.SRH_TOKEN }} -e SRH_CONNECTION_STRING="redis://redis:6379"

      # The following tests fail because of bugs with Upstash's implementation of Redis, NOT because of our library
      # So we remove them from the test suite
      - name: Remove JSON tests
        run: |
          rm ./pkg/commands/json_get.test.ts
          rm ./pkg/commands/json_mget.test.ts
          rm ./pkg/commands/json_objlen.test.ts

      - name: Run @upstash/redis Test Suite
        run: deno test -A ./pkg
        env:
          UPSTASH_REDIS_REST_URL: http://srh:80
          UPSTASH_REDIS_REST_TOKEN: ${{ env.SRH_TOKEN }}