name: Test @upstash/redis compatability
on:
  push:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:18
    services:
      redis:
        image: redis:6.2 # 6.2 is the Upstash compatible Redis version
      srh:
        image: hiett/serverless-redis-http:0.0.5-alpha
        env:
          SRH_MODE: env
          SRH_TOKEN: example_token
          SRH_CONNECTION_STRING: redis://redis:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./example
        run: yarn install

      - name: Run script
        working-directory: ./example
        run: yarn start
        env:
          REDIS_CONNECTION_URL: http://srh:80
